name: BetterIsland
version: ${project.version}
main: me.manaki.plugin.betterisland.BetterIsland
api-version: 1.16
depend: [ BentoBox ]
softdepend: [PlayerData, SantoryCore]
commands:
  islandupgrade:
    description: MankaiStep
    aliases: [iu, isnangcap, nangcapdao, isu]
